name: Dungeon
version: ${project.version}
main: ${main.class}
api-version: 1.13

depend:

libraries:
  - org.openjdk.nashorn:nashorn-core:15.4
  - redis.clients:jedis:4.3.0
  - biz.source_code:base64coder:2010-12-19
  - org.apache.commons:commons-math3:3.6.1
  - org.mariadb.jdbc:mariadb-java-client:3.1.4


authors: [ SimonSaltikov ]


